# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd server
          npm i
          pm2 stop 1
          pm2 save
          pm2 start 1
          pm2 save
          sudo service nginx restart
      - run: |
          cd client
          chmod 777 node_modules
          npm i
          pm2 stop 0
          pm2 save
          pm2 start 0
          pm2 save
          sudo service nginx restart
